// src/lib/Footer.svelte
<script>
</script>

<footer class="footer-outer">
  <div class="container footer-inner">
    <div class="footer-three-grid wow fadeIn animated" data-wow-delay="0.66s">
      <div class="column-1-3">
        <h1>CPSS Lab</h1>
      </div>
      <div class="column-2-3">
        <!-- TODO: 위치랑 저시기 그 뭐냐 수정 -->
        <p style="color: white;">
          중앙대학교 산업보안학과, 사이버물리시스템 보안 연구실<br />
          TEL. (02) 820-5935<br />
          주소: 서울시 동작구 흑석로 84, 310관 1139호<br />
        </p>
      </div>
    </div>

    <span class="border-bottom-footer"></span>

    <p class="copyright">
      &copy; 2024-2026 CPSS Lab. All rights reserved. Designed by <a
        href="https://github.com/karu-rress"
        target="_blank">karu-rress</a
      > &amp; esther.
    </p>
  </div>
</footer>

<style>
  .footer-outer {
    width: 100%;
    padding: 30px 20px;
    background: #2e3149;
  }
  .footer-outer .footer-inner {
    max-width: 1140px;
    margin: 0 auto;
  }

  .footer-outer .footer-three-grid {
    display: flex;
    justify-content: space-between;
    align-items: center;
    gap: 20px;
    flex-wrap: wrap;
  }

  .column-1-3,
  .column-2-3 {
    flex: 1;
    min-width: 250px;
  }

  .column-1-3 h1 {
    font-size: 32px;
    letter-spacing: 2px;
    font-weight: 600;
    color: #fff;
    margin: 0;
  }

  .column-2-3 p {
    color: #fff;
    line-height: 1.6;
    margin: 0;
  }

  .border-bottom-footer {
    height: 1px;
    width: 100%;
    border: none;
    background: #434769;
    display: block;
    margin: 20px 0;
  }

  .copyright {
    color: #767ba7;
    text-align: center;
    font-size: 13px;
    margin: 0;
  }
</style>

// next/src/components/layout/Footer.tsx
"use client";
import * as S from "./Footer.styles";

const Footer = () => {
  return (
    <S.FooterOuter>
      <S.FooterInner>
        <S.FooterGrid>
          <S.Column>
            <S.Title>CPSS Lab</S.Title>
          </S.Column>

          <S.Column>
            <S.Info>
              중앙대학교 산업보안학과, 사이버물리시스템 보안 연구실
              <br />
              TEL. (02) 820-5935
              <br />
              주소: 서울시 동작구 흑석로 84, 310관 1139호
            </S.Info>
          </S.Column>
        </S.FooterGrid>

        <S.Divider />

        <S.Copyright>
          © 2024 CPSS Lab. All rights reserved. <br />
          Originally designed by{" "}
          <S.Link
            href="https://github.com/karu-rress"
            target="_blank"
            rel="noopener noreferrer"
          >
            karu-rress
          </S.Link>{" "}
          & esther. <br />
          Redesigned by {" "}
          <S.Link
            href="https://github.com/xaerinoo"
            target="_blank"
            rel="noopener noreferrer"
          >
            xaerinoo
          </S.Link>.
        </S.Copyright>
      </S.FooterInner>
    </S.FooterOuter>
  )
}

export default Footer
